name: flutter_gallery_assets
description: Images and fonts for the Flutter gallery demo
version: 0.1.8
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: http://flutter.io
environment:
  sdk: '>=1.19.0 <3.0.0'
  flutter: '>=0.1.0 <2.0.0'

