name: bsdiff
description: Binary diff/patch algorithm based on bsdiff by Colin Percival.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/packages/tree/master/third_party/packages/bsdiff
version: 0.1.0

dev_dependencies:
  test: "^1.3.4"

environment:
  sdk: ">=2.1.1-dev.2.0 <3.0.0"
