name: args
version: 1.5.1
author: "Dart Team <misc@dartlang.org>"
homepage: https://github.com/dart-lang/args
description: >
 Library for defining parsers for parsing raw command-line arguments into
 a set of options and values using GNU and POSIX style options.

environment:
  sdk: '>=1.22.0 <3.0.0'

dev_dependencies:
  test: '^1.5.1'
