name: kernel
# Currently, kernel API is not stable and users should
# not depend on semver semantics when depending on this package.
version: 0.3.14
author: Dart Team <misc@dartlang.org>
description: Dart IR (Intermediate Representation)
homepage: https://github.com/dart-lang/sdk/tree/master/pkg/kernel
environment:
  sdk: '>=2.0.0-dev.48.0 <3.0.0'
dependencies:
  path: ^1.3.9
  args: '>=0.13.4 <2.0.0'
dev_dependencies:
  expect:
    path: ../expect
  front_end:
    path: ../front_end
  test:
    path: ../../third_party/pkg/test
  testing:
    path: ../testing
