# See https://github.com/dart-lang/mono_repo for details
dart:
  - stable

stages:
  - format_analyzer_tests:
    - group:
      - dartanalyzer: --fatal-infos --fatal-warnings .
      dart: [dev]
    - group:
      - dartfmt
      dart: [stable]
    - group:
      - dartanalyzer: --fatal-warnings .
      dart: [stable]
    - group:
      - test
      dart: [stable, dev]
