# Copyright (c) 2015, the Dart project authors.  Please see the AUTHORS file
# for details. All rights reserved. Use of this source code is governed by a
# BSD-style license that can be found in the LICENSE file.

branches:
  only:
    - dev

install:
  - ps: wget https://storage.googleapis.com/dart-archive/channels/stable/release/latest/sdk/dartsdk-windows-x64-release.zip -OutFile dart-sdk.zip
  - cmd: echo "Unzipping dart-sdk..."
  - cmd: 7z x dart-sdk.zip -o"C:\tools" -y > nul
  - set PATH=%PATH%;C:\tools\dart-sdk\bin
  - set PATH=%PATH%;%APPDATA%\Pub\Cache\bin
  - cmd: dart --version
  - pub get

build: off

test_script:
  - pub run test -j1
# using pub run pending resolution of https://github.com/dart-lang/linter/issues/1104  
#  - dart test\all.dart
