name: linter
version: 0.1.83

author: Dart Team <misc@dartlang.org>

description: >-
  The implementation of the lint rules supported by the analyzer framework.
  This package is not intended to be used directly.
homepage: https://github.com/dart-lang/linter
documentation: https://dart-lang.github.io/linter/lints

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  analyzer: ^0.35.3
  args: '>=1.4.0 <2.0.0'
  glob: ^1.0.3
  meta: ^1.0.2
  source_span: ^1.0.2
  yaml: ^2.1.2

dev_dependencies:
  cli_util: ^0.1.2
  dart_style: ^1.1.0
  github: ^4.0.1
  grinder: ^0.8.0
  markdown: ^2.0.0
  matcher: ^0.12.0
  path: ^1.2.0
  pub_semver: ^1.4.2
  test: ^1.0.0
