name: example
description: A progress_hud example

dependencies:
  flutter:
    sdk: flutter
  progress_hud:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
