# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
targets:
  $default:
    builders:
      json_serializable:
        generate_for:
        - example/*
        - test/default_value/*
        - test/generic_files/*
        - test/integration/*
        - test/kitchen_sink/*
        - test/literal/*

      build_web_compilers|entrypoint:
        generate_for:
        - test/default_value/**.browser_test.dart
        - test/generic_files/*.browser_test.dart
        - test/integration/*.browser_test.dart
        - test/kitchen_sink/**.browser_test.dart

      json_serializable|_internal:
        generate_for:
        - test/default_value/default_value.dart
        - test/kitchen_sink/kitchen_sink.dart
        - test/integration/json_test_example.dart
        - test/generic_files/generic_class.dart
        - test/integration/json_test_example.dart
        - test/integration/json_test_example.non_nullable.dart

builders:
  _internal:
    import: 'tool/test_builder.dart'
    builder_factories: ['internal']
    build_extensions:
      .dart:
      - .factories.dart
      - .g_any_map.dart
      - .g_any_map__checked.dart
      - .g_any_map__checked__non_nullable.dart
      - .g_any_map__non_nullable.dart
      - .g_exclude_null.dart
      - .g_exclude_null__non_nullable.dart
      - .g_explicit_to_json.dart
      - .g_non_nullable.dart
    build_to: source
    runs_before: ["json_serializable"]

  _doc_builder:
    import: "tool/doc_builder.dart"
    builder_factories: ["docBuilder"]
    build_extensions: {"lib/json_serializable.dart": ["doc/doc.md"]}
    build_to: source
    auto_apply: root_package
    runs_before: ["json_serializable"]
    required_inputs: ["doc/json_annotation_version.txt"]

  json_serializable:
    import: "package:json_serializable/builder.dart"
    builder_factories: ["jsonSerializable"]
    build_extensions: {".dart": ["json_serializable.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
